### ISSUE TITLE
did not generatr boux 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 

### ISSUE THREAD

**Issue by m1auch4t** [PadoreQ/bobux-generator#1]
scasm dindnt generatr b oux !1111: (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by PadoreQ** [comment]
what??

write a problem

**Comment by PadoreQ** [comment]
ok problem fixed
